### ISSUE TITLE
'Tag' support?

### ISSUE THREAD

**Issue by smgoller** [stevschmid/track-o-bot#74]
First off, track-o-bot is awesome. 

I know there's no way for track-o-bot to inherently know what deck is in use. But if the user could create/select an active tag that would be submitted along with every result, that would seem to be a simple way for the user to arbitrarily group match results. From a UI/UX perspective, having a "Tag" flyout menu on the main dropdown that has a list of tags created by the user, and an option at the bottom to create a new one. Also, add a tag management tab in settings.

I'm not asking you to implement this, I'm wondering if this is a feature you would consider including if someone were to work on it and submit a pull request.

**Comment by stevschmid** [comment]
Hi Sean

Thanks for the suggestion.

Having to manually select the deck every time you change it ingame is too complicated / intrusive. For instance, how do you select the tag if you are running the game fullscreen? And wouldn't you get frustrated when you forget to change the deck? Track-o-Bot is about simplicity through automation. That's why you need to specify your decks with a few key cards once in your profile and then you're all set. From now on, Track-o-Bot assigns the deck for you automatically: You can focus on your game at hand. 

Is the current system the very best when it comes to deck assignment? Certainly not. Is it the best when it comes to automatically assign the deck without requiring any input of the user? I think so!

If you have a suggestion to make the deck selection better while keeping it non-intrusive for the user, please feel free to post it here!

**Comment by smgoller** [comment]
You're absolutely right in that it's still cumbersome, and I humbly retract the change to the client. :) What do you think about being able to assign tags to matches via the website? That keeps the client interface streamlined, but allows post-play-session management and analysis. It's functionality that doesn't affect the existing workflow at all, but allows people to organize their match history how they want.

**Comment by stevschmid** [comment]
Adding tags to matches in the profile would definitely be better, yet I think it's not a feature most people would use. But maybe I'm wrong :) I'm open to add such a feature if enough people are interested in the idea.

**Comment by stevschmid** [comment]
Tag support is live since a couple of weeks ago.
