### ISSUE TITLE
Undefined decks in deck stats

### ISSUE THREAD

**Issue by rshareef** [stevschmid/track-o-bot#78]
Firstly, great tracking program, doesn't impede my gameplay at all.

I was just wondering if in the deck stats tab there could be an undefined deck row in the versus section. Mainly so one can know if they are facing decks that they haven't entered into the tracker. Plus it will show how many unknown brews you face.

Thanks for all the hard work!

**Comment by cybergollum** [comment]
[not a developer of this program, just man who wonders]

Since mine track-o-bot shows correct statistics as expected. I am interesting in how it looks like. How many deck you created? Is there a possibility that you accidently created empty decks and didn't notice it? I remember few times when It happened to me. Maybe it is your case too?

https://cloud.githubusercontent.com/assets/12521072/8225416/f0f2aa88-159c-11e5-9d7b-3e4cd61f6bb5.png
https://cloud.githubusercontent.com/assets/12521072/8225638/c354fb00-159f-11e5-9e08-2f08d536a23c.png (after adding empty deck statistics didn't change).

Can you make screenshot? (since I am not offical person here, you can ignore my request)

**Comment by rshareef** [comment]
I think I may not have been clear enough. This is a feature request and not a bug I found.

Imagine that you have added 9 decks, one for each class. One of those decks is Handlock, and you use only a couple of identifying cards such as Ancient Watcher, Sunfury Protector, Twilight Drake, Mountain Giant and Molten Giant.

Now if I am playing as Handlock my statistics are collected in the Decks tab correctly. Now if I switch decks and play a Zoo Warlock Aggro deck only the classes tabs collects the statistics. I can usually just add a deck I know to my deck list and there is no problem, Zoo will then appear in the decks tab.

Now instead of me playing Zoo, imagine I am Handlock and I am playing against Zoo, that game won't be added to the Handlock stats in the Decks Tab. It will show up as part of the Warlock stat in the Classes tab. I would like to see how my deck, Handlock, performs against unknown decks, decks I have not entered into my list of decks.

![image](https://cloud.githubusercontent.com/assets/2547411/8267392/1a22317a-172e-11e5-8597-cd7655d5da3d.png)

**Comment by stevschmid** [comment]
I think this is a good idea. Could you reopen this issue in the website repo @ https://github.com/stevschmid/trackobot.com? Thanks!
